Homework_4
katemalash/Rv-074.PythonCore pull request #15
Opened 2021-04-26 11:11 UTC by vadym-yats

2021-05-07 13:15 UTC, katemalash requested changes
Please improve task 2

2021-05-31 10:05 UTC, vadym-yats commented on Yatsentiuk_Vadym/HW4/hw4_2.py
> +    height_triangle = int(input("Enter the height triangle: "))
Already fixed, thanks!

2021-05-31 10:05 UTC, vadym-yats commented on Yatsentiuk_Vadym/HW4/hw4_3.py
> +    print("This number is 0, its length is 1 character")
Thanks!

2021-05-31 10:06 UTC, vadym-yats commented on Yatsentiuk_Vadym/HW4/hw4_5.py
> +elif amount%200 != 0 and amount%100 == 0:
She is really not needed, thank you.

2021-05-31 10:06 UTC, vadym-yats commented on Yatsentiuk_Vadym/HW4/hw4_6.py
> +    print("Your place on top, on the compartment")
:)

2021-06-04 11:02 UTC, katemalash approved these changes
Please merge this pull-request

2021-06-05 10:56 UTC, merged