homework 4
katemalash/Rv-074.PythonCore pull request #18
Opened 2021-04-27 13:20 UTC by maintf

2021-05-18 11:36 UTC, katemalash requested changes
Please fix task 2

2021-05-18 11:36 UTC, katemalash commented on Mykhaliuk/HW4/1.py
> +century = (year - 1) // 100 + 1
Why do you use year - 1 here?

2021-05-18 11:36 UTC, katemalash commented on Mykhaliuk/HW4/2.py
> +print('figure perimeter:', perimetr)
It was required to calculate square here, not perimeter.

2021-05-18 11:36 UTC, katemalash commented on Mykhaliuk/HW4/3.py
> +    print("you've entered", positivity, number_of_didgits, '- didgit number')
Nice decision!

2021-05-18 11:36 UTC, katemalash commented on Mykhaliuk/HW4/5.py
> +print ("1:", amount // 1)
This is working Way

2021-05-18 11:36 UTC, katemalash commented on Mykhaliuk/HW4/4.py
> +root.mainloop()
Perfect Way

2021-05-20 15:10 UTC, maintf commented on Mykhaliuk/HW4/1.py
> +century = (year - 1) // 100 + 1
so that year 2000 still belongs to 20th century

2021-06-04 11:06 UTC, katemalash commented on Mykhaliuk/HW4/1.py
> +century = (year - 1) // 100 + 1
Nice)

2021-06-04 11:07 UTC, katemalash approved these changes
Now you can merge this pull-request

2021-06-04 11:07 UTC, katemalash commented on Mykhaliuk/HW4/2.py
> +print('figure square:', square)
Good Now!

2021-06-04 13:37 UTC, merged