homework3
katemalash/Rv-074.PythonCore pull request #5
Opened 2021-04-21 09:28 UTC by zFalkRumz

Sending completed tasks 1-5, tasks 6-7 will be sent soon

2021-04-21 18:17 UTC, katemalash requested changes
Please fix Calc task :-)

2021-04-21 18:17 UTC, katemalash commented on Freyak/HW3/PAcrircle.py
> +import math
Just advise: it's good practice to add 2 empty lines after imports

2021-04-21 18:17 UTC, katemalash commented on Freyak/HW3/PAcrircle.py
> +if choise < 1:
is it possible to combine this and the next check in the single "if"?

2021-04-21 18:17 UTC, katemalash commented on Freyak/HW3/PAcrircle.py
> +    print("S = ", radius**2*math.pi)
'*' has lower priority than '**', so it's recomeded to make spaces around it

2021-04-21 18:17 UTC, katemalash commented on Freyak/HW3/Pifagor.py
> +from math import sqrt
It's recommended to add 2 empty lines after imports

2021-04-21 18:17 UTC, katemalash commented on Freyak/HW3/Pifagor.py
> +    print("Hypotenuse = ", sqrt(FirKatet**2+SecKatet**2))
'+' has lower priority than "*"

2021-04-21 18:17 UTC, katemalash commented on Freyak/HW3/calc.py
> +    print(bytes / 1000, "Kb")
are you sure, 1000 is correct value?

2021-04-21 18:17 UTC, katemalash commented on Freyak/HW3/calc.py
> +    print(bytes / 1000000, "Mb")
Are you sure. it's correct value?

2021-04-21 18:32 UTC, zFalkRumz commented on Freyak/HW3/PAcrircle.py
> +if choise < 1:
ooops, pushed   incorrect save:)

2021-04-22 12:03 UTC, katemalash approved these changes
Looks good to me

2021-04-22 12:30 UTC, merged