Lesson3 homework
katemalash/Rv-074.PythonCore pull request #6
Opened 2021-04-21 18:39 UTC by deb-lab

Hello.
Seems I'm complete some tasks and ready to code review. 
Thanks.

2021-04-22 13:04 UTC, deb-lab commented on Hrebenevych/HW3/task1.py
> +b = 20
Little problems with naming variables.

2021-04-23 06:24 UTC, katemalash requested changes
Please fix the task 2

2021-04-23 06:24 UTC, katemalash commented on Hrebenevych/HW3/task4.py
> +pi = 3.14159265359
Is it possible to use another way?

2021-04-23 06:24 UTC, katemalash commented on Hrebenevych/HW3/task2.py
> +kilobytes = size / 1000
Are you sure you use the correct calculations?

2021-04-23 20:34 UTC, deb-lab commented on Hrebenevych/HW3/task4.py
> +pi = 3.14159265359
We can use `math.pi` from the math module.

2021-04-23 20:37 UTC, deb-lab commented on Hrebenevych/HW3/task5.py
> +        'two': None
Changed. Thanks.

2021-04-23 20:38 UTC, deb-lab commented on Hrebenevych/HW3/task2.py
> +kilobytes = size / 1000
Changed to 1024.

2021-04-27 11:43 UTC, katemalash approved these changes
Looks good now. You can merge your pull-request

2021-04-27 11:45 UTC, merged